# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aday Hepimiz
description: >- # this means to ignore newlines"
  "Aday ben değilim, #adayhepimiz"

# Copy
# Fill in your copy for the title and steps here
# 
title-text: "Aday Hepimiz!"
step-1: "Profil fotoğrafını yükle."
step-2: "Boyutunu ve yönünü ayarla."
step-3: "Çerçeveni seç."
step-4: "Yeni profil fotoğrafını indir!"
step-5: "Sosyal medyada #adayhepimiz etiketiyle paylaşmayı unutma!"
footer-text: "Aday Hepimiz - 2023"

# Buttons and upload form
# 
upload-text: "Fotoğraf Yükle"
download-button-text: "İndir"

# Logo & Favicon
# 
logo: "logo.png"
favicon: "favicon.ico"

# Footer links
# 
# footer-links:
#   - text: "Awesome page 1"
#     link: "http://google.com"

#   - text: "Other page 2"
#     link: "http://google.com"

#   - text: "Things!"
#     link: "http://google.com"

# Open Graph and Twitter Cards
#
og-title: Aday Hepimiz
og-description: Başlıyoruz 
og-url: https://adayhepimiz.com
og-image: "og-image.png"
og-image-width: 1280
og-image-height: 640
twitter-card: summary_large_image
twitter-description: "Aday ben değilim, #adayhepimiz"
twitter-image: "og-image.png"
twitter-handle: "@kilicdarogluk"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
  - README.md
  - docs
